import type { NewOrganization, Organization } from "@/db/schema/organizations";
import type { NewUser, User } from "@/db/schema/users";
import type { NewClient, Client } from "@/db/schema/clients";
import type { NewInvoice, Invoice } from "@/db/schema/invoices";
import type { NewInvoiceItem } from "@/db/schema/invoice-items";
import type { NewExpense, Expense } from "@/db/schema/expenses";
import { COUNTRY_BASE, CURRENCY, LANGUAGE, COUNTRY_CONTEXT, INVOICE_STATUS, EXPENSE_CATEGORY, PAYMENT_METHOD } from "./constants";

export const mockOrganization: NewOrganization = {
  name: "Helion City",
  countryBase: COUNTRY_BASE.DE,
  defaultCurrency: CURRENCY.EUR,
  taxIdDe: "DE123456789",
  taxIdMx: "RFC123456789",
  addressLine1: "Musterstraße 123",
  city: "Berlin",
  postalCode: "10115",
  country: "Germany",
};

export const mockUser: Omit<NewUser, "authUserId" | "organizationId"> = {
  role: "owner",
  email: "admin@helioncity.com",
};

export const mockClients: Omit<NewClient, "organizationId">[] = [
  {
    name: "Acme Corporation",
    contactPerson: "John Doe",
    email: "john@acme.com",
    phone: "+49 30 12345678",
    addressLine1: "Unter den Linden 1",
    city: "Berlin",
    postalCode: "10117",
    country: "Germany",
    defaultCurrency: CURRENCY.EUR,
    defaultLanguage: LANGUAGE.EN,
    taxId: "DE987654321",
  },
  {
    name: "Tech Solutions MX",
    contactPerson: "María García",
    email: "maria@techsolutions.mx",
    phone: "+52 55 12345678",
    addressLine1: "Av. Reforma 123",
    city: "Ciudad de México",
    postalCode: "06500",
    country: "Mexico",
    defaultCurrency: CURRENCY.MXN,
    defaultLanguage: LANGUAGE.ES,
    taxId: "TEC123456789",
  },
  {
    name: "Global Services Ltd",
    contactPerson: "Jane Smith",
    email: "jane@globalservices.com",
    phone: "+1 555 1234567",
    addressLine1: "123 Main St",
    city: "New York",
    postalCode: "10001",
    country: "USA",
    defaultCurrency: CURRENCY.USD,
    defaultLanguage: LANGUAGE.EN,
  },
];

export const mockInvoiceItems: Omit<NewInvoiceItem, "invoiceId">[] = [
  {
    description: "Web Development Services",
    quantity: "40.00",
    unitPrice: "150.00",
    taxRate: "19.00",
    lineSubtotal: "6000.00",
    lineTax: "1140.00",
    lineTotal: "7140.00",
    sortOrder: 0,
  },
  {
    description: "Consulting Hours",
    quantity: "10.00",
    unitPrice: "200.00",
    taxRate: "19.00",
    lineSubtotal: "2000.00",
    lineTax: "380.00",
    lineTotal: "2380.00",
    sortOrder: 1,
  },
];

export const mockInvoices: Omit<NewInvoice, "organizationId" | "clientId" | "invoiceNumber">[] = [
  {
    issueDate: "2024-01-15",
    dueDate: "2024-02-15",
    currency: CURRENCY.EUR,
    language: LANGUAGE.EN,
    status: INVOICE_STATUS.PAID,
    subtotalAmount: "8000.00",
    taxAmount: "1520.00",
    totalAmount: "9520.00",
    notes: "Thank you for your business!",
    countryContext: COUNTRY_CONTEXT.DE,
  },
  {
    issueDate: "2024-02-01",
    dueDate: "2024-03-01",
    currency: CURRENCY.EUR,
    language: LANGUAGE.DE,
    status: INVOICE_STATUS.SENT,
    subtotalAmount: "5000.00",
    taxAmount: "950.00",
    totalAmount: "5950.00",
    countryContext: COUNTRY_CONTEXT.DE,
  },
  {
    issueDate: "2024-01-20",
    dueDate: "2024-02-20",
    currency: CURRENCY.MXN,
    language: LANGUAGE.ES,
    status: INVOICE_STATUS.PAID,
    subtotalAmount: "50000.00",
    taxAmount: "8000.00",
    totalAmount: "58000.00",
    countryContext: COUNTRY_CONTEXT.MX,
  },
  {
    issueDate: "2024-03-01",
    dueDate: "2024-04-01",
    currency: CURRENCY.EUR,
    language: LANGUAGE.EN,
    status: INVOICE_STATUS.OVERDUE,
    subtotalAmount: "3000.00",
    taxAmount: "570.00",
    totalAmount: "3570.00",
    countryContext: COUNTRY_CONTEXT.DE,
  },
];

export const mockExpenses: Omit<NewExpense, "organizationId" | "id" | "createdAt" | "updatedAt">[] = [
  {
    vendorName: "AWS",
    description: "Cloud hosting services",
    amount: "150.00",
    currency: CURRENCY.EUR,
    taxRate: "19.00",
    taxAmount: "28.50",
    totalAmount: "178.50",
    category: EXPENSE_CATEGORY.SOFTWARE,
    countryContext: COUNTRY_CONTEXT.DE,
    deductible: true,
    date: "2024-01-05",
    paymentMethod: PAYMENT_METHOD.CARD,
  },
  {
    vendorName: "Office Rent",
    description: "Monthly office rent",
    amount: "1200.00",
    currency: CURRENCY.EUR,
    taxRate: "19.00",
    taxAmount: "228.00",
    totalAmount: "1428.00",
    category: EXPENSE_CATEGORY.RENT,
    countryContext: COUNTRY_CONTEXT.DE,
    deductible: true,
    date: "2024-01-01",
    paymentMethod: PAYMENT_METHOD.TRANSFER,
  },
  {
    vendorName: "Figma",
    description: "Design tool subscription",
    amount: "12.00",
    currency: CURRENCY.USD,
    taxRate: "0.00",
    taxAmount: "0.00",
    totalAmount: "12.00",
    category: EXPENSE_CATEGORY.SOFTWARE,
    countryContext: COUNTRY_CONTEXT.OTHER,
    deductible: true,
    date: "2024-01-10",
    paymentMethod: PAYMENT_METHOD.CARD,
  },
  {
    vendorName: "Taxi CDMX",
    description: "Business travel",
    amount: "500.00",
    currency: CURRENCY.MXN,
    taxRate: "16.00",
    taxAmount: "80.00",
    totalAmount: "580.00",
    category: EXPENSE_CATEGORY.TRAVEL,
    countryContext: COUNTRY_CONTEXT.MX,
    deductible: true,
    date: "2024-01-15",
    paymentMethod: PAYMENT_METHOD.CARD,
  },
  {
    vendorName: "Starbucks",
    description: "Client meeting",
    amount: "25.00",
    currency: CURRENCY.EUR,
    taxRate: "7.00",
    taxAmount: "1.75",
    totalAmount: "26.75",
    category: EXPENSE_CATEGORY.OFFICE,
    countryContext: COUNTRY_CONTEXT.DE,
    deductible: false,
    date: "2024-01-20",
    paymentMethod: PAYMENT_METHOD.CARD,
  },
];

